name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - shell: bash
      run: corepack enable

    - name: Check out code
      uses: actions/setup-node@v4
      with:
          fetch-depth: 2

    - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

    - name: Install dependencies
        run: pnpm install --frozen-lockfile
