import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { appConfig } from "@/app/config";
import { Navbar } from "@/domains/ui/navbar/navbar";
import { getLocale } from "next-intl/server";
import { type Locale } from "@/i18n/config";
import { Providers } from "@/domains/providers";
import { Toaster } from "@pfl-wsr/ui";
import { Dock } from "@/domains/ui/navbar/dock";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: appConfig.name,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = (await getLocale()) as Locale;
  return (
    <html lang={locale}>
      <body
        className={`${inter.className} bg-background text-foreground antialiased`}
      >
        <Providers>
          <div className="flex h-screen flex-col">
            <Navbar />
            <div className="flex-1 overflow-auto p-4">
              <div className="container mx-auto">{children}</div>
            </div>
            <Dock />
          </div>

          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
